### ISSUE TITLE
Error installing .net framework 4.6.1 with cDotNetFramework resource

### ISSUE THREAD

**Issue by gigi81** [guitarrapc/GraniResource#61]
I'm trying to use the cDotNetFramework resource but with not much luck.
This is my configuration:

cDotNetFramework DotNet461
{
    KB = "KB3102436"
    InstallerPath = "$software\NDP461-KB3102436-x86-x64-AllOS-ENU.exe"
    Ensure = "Present"
    NoRestart = $false
    LogPath = "$logs\DotNet461.log"
}

And these are the errors I can see on the windows event log:

Job {22503149-FCDE-11E5-80CA-005056B81B83} : 
Message Could not find KB from Windows Hotfix list. KB : KB3102436 
HResult -2146233087 
StackTrack    at System.Management.Automation.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Job {22503149-FCDE-11E5-80CA-005056B81B83} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [cDotNetFramework]DotNet461 and Source Info is D:\BuildAgent\work\b909d824977baca3\infra\dsc\TeamCity.ps1::26::3::cDotNetFramework. Error Message is PowerShell DSC resource Grani_DotNetFramework  failed to execute Set-TargetResource functionality with error message: Could not find KB from Windows Hotfix list. KB : KB3102436 .

Job {22503149-FCDE-11E5-80CA-005056B81B83} : 
MIResult: 1
Error Message: PowerShell DSC resource Grani_DotNetFramework  failed to execute Set-TargetResource functionality with error message: Could not find KB from Windows Hotfix list. KB : KB3102436 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI

Any help would be appreciated.
Thanks

**Comment by FabienLavocat** [comment]
You must have your Windows Server with the Windows Update KB3102436
That's a requirement to install the .NET Framework 4.6

**Comment by guitarrapc** [comment]
seems can close.
