### ISSUE TITLE
Sporadic error after "Test-DscConfiguration"

### ISSUE THREAD

**Issue by Denis1983** [guitarrapc/GraniResource#69]
Sporadic error after "Test-DscConfiguration"

VERBOSE: [FORS559A]: LCM:  [ *FAILED*Test     ]     Completed processing test operation. The operation failed.
Importing module Grani_ScheduleTask failed with error - Cannot add type. The type name 'EnsureType' already exists.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost

**Comment by guitarrapc** [comment]
Thank you for reporting. It seems like instance already exists and access to Add-Type. Will check it and get you back in next week. (Sorry I'm on business trip for this week.)

**Comment by guitarrapc** [comment]
I've published 3.7.8.3 with fix for you. Seems not happen anymore at my lab.

![image](https://cloud.githubusercontent.com/assets/3856350/26511332/89c1610e-429c-11e7-834f-6bdd7293ca14.png)

Please check it.
> https://www.powershellgallery.com/packages/GraniResource/3.7.8.3
