### ISSUE TITLE
Update Grani_Download to support new TLS versions

### ISSUE THREAD

**Issue by rajbos** [guitarrapc/GraniResource#84]
File: GraniResource/DSCResources/Grani_Download/Grani_Download.psm1

Ran into an issue in an ARM template where this resource was used. See [here](https://github.com/Azure/azure-quickstart-templates/pull/4840). 

Fixed it by setting the TLS version before the download:
``` powershell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 -bor [System.Net.SecurityProtocolType]::Tls11 -bor [System.Net.SecurityProtocolType]::Tls
```

I suggest we add that here as well, to prevent any issues when the host disables older TLS versions.

If you want, I can sent it in as a pull request, but thought it would be nice to open up an issue first.

**Comment by guitarrapc** [comment]
Wonderful, I forgot to set it for Resources. Thank you.
Pull Request is always welcome:) If you can wait, I will patch tonight.

**Comment by guitarrapc** [comment]
Will release to gallery as soon as I home. (now i'm at mac environment.)

**Comment by rajbos** [comment]
No rush, fix is already present where I needed it, happy to contribute 👍 .

**Comment by guitarrapc** [comment]
released:)
https://www.powershellgallery.com/packages/GraniResource/3.7.11.0
https://github.com/guitarrapc/GraniResource/releases/tag/ver.3.7.11.0
